name: Prebuild check and build

on:
  pull_request:
    branches:
      - develop

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0

      - name: Install modules
        run: cd frontend && yarn install --frozen-lockfile

      - name: Run ESLint and Prettier
        run: cd frontend && yarn check-format && yarn check-lint

      - name: Build NextJS project
        run: cd frontend && yarn build
